reaction-columns = [rxn_smiles]
num-workers = 20
keep-h = true
add-h = true
molecule-featurizers = [charge]
data-path = /home/akshatz/bond_order_free/barriers_cycloadd/dataset/cycloadd_data.csv
aggregation = norm
no-batch-norm = true
target-columns = [G_act]
task-type = regression
epochs = 200
splits-file = /home/akshatz/bond_order_free/barriers_cycloadd/dataset/splits.json
batch-size = 128
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
message-hidden-dim = 2100
depth = 3
dropout = 0.1
activation = RELU
aggregation-norm = 100
ffn-hidden-dim = 300
ffn-num-layers = 1
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
warmup-epochs = 28
init-lr = 0.0003664195323771416
max-lr = 0.0004417937833364825
final-lr = 0.00016006258615489774
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
