reaction-columns = [smiles]
num-workers = 20
keep-h = true
molecule-featurizers = [charge]
data-path = /home/akshatz/bond_order_free/barriers_rgd1/dataset/rgd1_data.csv
aggregation = norm
no-batch-norm = true
task-type = regression
epochs = 50
splits-file = /home/akshatz/bond_order_free/barriers_rgd1/dataset/splits.json
batch-size = 64
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
message-hidden-dim = 600
depth = 5
dropout = 0.2
activation = RELU
aggregation-norm = 100
ffn-hidden-dim = 1600
ffn-num-layers = 2
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
warmup-epochs = 2
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
