num-workers = 20
accelerator = gpu
devices = 1,
keep-h = true
add-h = true
config-path = ../../rigr_h298_50k/run4_baseline_best/best_config.toml
data-path = ../dataset/run4/data_run_4.csv
ensemble-size = 5
aggregation = sum
no-batch-norm = true
weight-column = weights
target-columns = [H298_kcal]
task-type = regression
epochs = 100
num-folds = 1
splits-file = ../dataset/run4/splits.json
pytorch-seed = 21
smiles-columns = [resonance_smis]
batch-size = 64
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
message-hidden-dim = 300
depth = 5
dropout = 0.0
activation = RELU
aggregation-norm = 100
ffn-hidden-dim = 1700
ffn-num-layers = 1
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
warmup-epochs = 2
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
data-seed = 0
