smiles-columns = [resonance_smis]
num-workers = 20
keep-h = true
add-h = true
data-path = ../dataset/final_data_set.csv
aggregation = sum
no-batch-norm = true
target-columns = [H298_kcal]
task-type = regression
epochs = 100
splits-file = ../dataset/splits.json
batch-size = 64
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
message-hidden-dim = 300
depth = 5
dropout = 0.0
activation = RELU
aggregation-norm = 100
ffn-hidden-dim = 2100
ffn-num-layers = 1
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
warmup-epochs = 2
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
