reaction-columns = [AAM]
num-workers = 20
keep-h = true
molecule-featurizers = [charge]
data-path = /home/akshatz/bond_order_free/barriers_e2/dataset/e2_data.csv
aggregation = norm
no-batch-norm = true
task-type = regression
epochs = 200
splits-file = /home/akshatz/bond_order_free/barriers_e2/dataset/splits.json
batch-size = 16
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
message-hidden-dim = 1300
depth = 2
dropout = 0.0
activation = RELU
aggregation-norm = 100
ffn-hidden-dim = 500
ffn-num-layers = 2
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
warmup-epochs = 68
init-lr = 1.714469907542827e-05
max-lr = 0.0004964186361380277
final-lr = 2.1813076308015214e-05
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
