reaction-columns = [AAM]
num-workers = 20
keep-h = true
add-h = true
molecule-featurizers = [charge]
data-path = /home/akshatz/bond_order_free/barriers_sn2/dataset/sn2_data.csv
aggregation = norm
no-batch-norm = true
task-type = regression
epochs = 200
splits-file = /home/akshatz/bond_order_free/barriers_sn2/dataset/splits.json
batch-size = 128
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
message-hidden-dim = 1600
depth = 5
dropout = 0.05
activation = RELU
aggregation-norm = 100
ffn-hidden-dim = 2300
ffn-num-layers = 1
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
warmup-epochs = 73
init-lr = 2.2752822334355665e-05
max-lr = 0.0004363038732215559
final-lr = 9.407433295007094e-06
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
